
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: Marie
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: cyclhome_database
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
    driver: local
